name: CI
on: [push]
jobs: 
  sast-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Rund Bandit Scan
      run: bandit -r -ll -ii -f json -o bandit-report.json .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  
  image_scan:
    name: Build Image nad Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t devsecops:0.1 .

    - name: Setup Docker Scout and Scan Docker Image
      run: |
         curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
         sh install-scout.sh
         docker login -u ${{REPO_USER}} -p ${{REPO_PWD}}
         docker scout quickview
         docker scout cves
  
